# -*- coding: utf-8 -*-
"""AI_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfYiZx1_KpUxWBx4DGCeLRESSb-Irwp5
"""

# 8 Puzzle Problem using Depth-First Search with Depth Limit (IDDFS)

def print_board(state):
    for i in range(0, 9, 3):
        print(state[i:i+3])
    print()


def get_neighbors(state):
    neighbors = []

    blank = state.index(0)
    row = blank // 3
    col = blank % 3

    moves = [
        (-1, 0),  # Up
        (1, 0),   # Down
        (0, -1),  # Left
        (0, 1)    # Right
    ]

    for dr, dc in moves:
        new_row = row + dr
        new_col = col + dc

        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_blank = new_row * 3 + new_col

            new_state = list(state)

            new_state[blank], new_state[new_blank] = \
                new_state[new_blank], new_state[blank]

            neighbors.append(tuple(new_state))

    return neighbors


def depth_limited_dfs(state, goal, visited, path, depth_limit):
    if state == goal:
        return path
    if depth_limit <= 0:
        return None

    visited.add(state)

    for neighbor in get_neighbors(state):
        if neighbor not in visited:
            result = depth_limited_dfs(
                neighbor,
                goal,
                visited,
                path + [neighbor],
                depth_limit - 1
            )
            if result is not None:
                return result

    visited.remove(state)
    return None


def iddfs(initial, goal, max_depth=100):
    for depth in range(max_depth):
        visited = set()
        result = depth_limited_dfs(initial, goal, visited, [initial], depth)
        if result is not None:
            return result
    return None



initial = (
    5, 4, 0,
    6, 1, 8,
    7, 3, 2
)

goal = (
    1, 2, 3,
    4, 5, 6,
    7, 8, 0
)


solution = iddfs(initial, goal, max_depth=30)

if solution:
    print("Solution found!")
    print("Number of moves:", len(solution) - 1)

    for step, state in enumerate(solution):
        print("Step", step)
        print_board(state)
else:
    print("No solution found within depth limit.")

# 8 Puzzle Problem using Depth-First Search with Depth Limit (IDDFS)

def print_board(state):
    for i in range(0, 9, 3):
        print(state[i:i+3])
    print()


def get_neighbors(state):
    neighbors = []

    blank = state.index(0)
    row = blank // 3
    col = blank % 3


    moves = [
        (-1, 0),  # Up
        (1, 0),   # Down
        (0, -1),  # Left
        (0, 1)    # Right
    ]

    for dr, dc in moves:
        new_row = row + dr
        new_col = col + dc

        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_blank = new_row * 3 + new_col

            new_state = list(state)


            new_state[blank], new_state[new_blank] = \
                new_state[new_blank], new_state[blank]

            neighbors.append(tuple(new_state))

    return neighbors


def depth_limited_dfs(state, goal, visited, path, depth_limit):
    if state == goal:
        return path
    if depth_limit <= 0:
        return None

    visited.add(state)

    for neighbor in get_neighbors(state):
        if neighbor not in visited:
            result = depth_limited_dfs(
                neighbor,
                goal,
                visited,
                path + [neighbor],
                depth_limit - 1
            )
            if result is not None:
                return result

    visited.remove(state)
    return None


def iddfs(initial, goal, max_depth=100):
    for depth in range(max_depth):
        visited = set()
        result = depth_limited_dfs(initial, goal, visited, [initial], depth)
        if result is not None:
            return result
    return None


initial = (
    5, 4, 0,
    6, 1, 8,
    7, 3, 2
)

goal = (
    1, 2, 3,
    4, 5, 6,
    7, 8, 0
)


solution = iddfs(initial, goal, max_depth=30)

if solution:
    print("Solution found!")
    print("Number of moves:", len(solution) - 1)

    for step, state in enumerate(solution):
        print("Step", step)
        print_board(state)
else:
    print("No solution found within depth limit.")