# -*- coding: utf-8 -*-
"""AI_lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyVh1zLTd78RV4O1BLdOjlGthMIOlLN7
"""

# Tic-Tac-Toe Game

board = [' ' for _ in range(9)]

def display_board():
    print()
    print(board[0] + " | " + board[1] + " | " + board[2])
    print("--+---+--")
    print(board[3] + " | " + board[4] + " | " + board[5])
    print("--+---+--")
    print(board[6] + " | " + board[7] + " | " + board[8])
    print()

def check_winner(player):
    winning_positions = [
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 3, 6],
        [1, 4, 7],
        [2, 5, 8],
        [0, 4, 8],
        [2, 4, 6]
    ]

    for position in winning_positions:
        if (board[position[0]] == player and
            board[position[1]] == player and
            board[position[2]] == player):
            return True

    return False

def board_full():
    for cell in board:
        if cell == ' ':
            return False
    return True

def play_game():
    current_player = 'X'

    while True:
        display_board()

        try:
            position = int(input(
                f"Player {current_player}, enter position (1-9): "
            ))
        except ValueError:
            print("Please enter a number.")
            continue

        if position < 1 or position > 9:
            print("Enter a position between 1 and 9.")
            continue

        position -= 1

        if board[position] != ' ':
            print("Position already occupied.")
            continue

        board[position] = current_player

        if check_winner(current_player):
            display_board()
            print(f"Player {current_player} wins!")
            break

        if board_full():
            display_board()
            print("Game Draw!")
            break

        if current_player == 'X':
            current_player = 'O'
        else:
            current_player = 'X'


play_game()

# Vacuum Cleaner - Goal Based Agent

def goal_based_agent(location, status_A, status_B):


    if status_A == "Clean" and status_B == "Clean":
        return "Goal Achieved"


    if location == "A" and status_A == "Dirty":
        return "Suck"

    if location == "B" and status_B == "Dirty":
        return "Suck"


    if location == "A" and status_B == "Dirty":
        return "Move Right"

    if location == "B" and status_A == "Dirty":
        return "Move Left"


def run_goal_based_agent():

    location = input("Enter initial location (A/B): ")
    status_A = input("Enter status of Room A (Clean/Dirty): ")
    status_B = input("Enter status of Room B (Clean/Dirty): ")

    while True:

        print("\n-------------------------")
        print("Location :", location)
        print("Room A   :", status_A)
        print("Room B   :", status_B)

        action = goal_based_agent(
            location, status_A, status_B
        )

        print("Action   :", action)

        if action == "Goal Achieved":
            print("\nGoal achieved: Both rooms are clean.")
            break

        elif action == "Suck":
            if location == "A":
                status_A = "Clean"
            else:
                status_B = "Clean"

        elif action == "Move Right":
            location = "B"

        elif action == "Move Left":
            location = "A"


run_goal_based_agent()

# Vacuum Cleaner - Simple Reflex Agent

def simple_reflex_agent(location, status):
    if status == "Dirty":
        return "Suck"

    if location == "A":
        return "Move Right"

    if location == "B":
        return "Move Left"


def run_simple_reflex_agent():
    location = input("Enter initial location (A/B): ")
    status_A = input("Enter status of Room A (Clean/Dirty): ")
    status_B = input("Enter status of Room B (Clean/Dirty): ")

    while True:
        if location == "A":
            status = status_A
        else:
            status = status_B

        print("\nLocation:", location)
        print("Status:", status)

        action = simple_reflex_agent(location, status)
        print("Action:", action)

        if action == "Suck":
            if location == "A":
                status_A = "Clean"
            else:
                status_B = "Clean"

        elif action == "Move Right":
            location = "B"

        elif action == "Move Left":
            location = "A"

        if status_A == "Clean" and status_B == "Clean":
            print("\nBoth rooms are clean.")
            break


run_simple_reflex_agent()